#!/usr/bin/env bash


# when using a fresh machine, dont forget to install brew first. 

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# ghostty 
rm -rf "$HOME/.config/ghostty"
ln -s "$DOTFILES/ghostty" "$HOME/.config/ghostty" 

# tmux
rm -rf "$HOME/.tmux.conf"
ln -s "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"

# scripts
mkdir -p "$HOME/.local/bin"

rm -rf "$HOME/.local/bin/t"
ln -s "$DOTFILES/scripts/t" "$HOME/.local/bin/t"

# old nvim config
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim 

# test 
rm -rf "$HOME/.config/test"
ln -s "$DOTFILES/test" "$HOME/.config/test" 

# new nvim config 
rm -rf "$HOME/.config/lvim"
ln -s "$DOTFILES/lvim" "$HOME/.config/lvim" 

# zsh stuff 
rm -rf "$HOME/.zshrc"
ln -s "$DOTFILES/zsh/zshrc" "$HOME/.zshrc"

# install oh-my-zsh if missing
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
fi

# custom plugings
ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
[ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]          || git clone https://github.com/zsh-users/zsh-autosuggestions          "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
[ -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]      || git clone https://github.com/zsh-users/zsh-syntax-highlighting      "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
[ -d "$ZSH_CUSTOM/plugins/zsh-history-substring-search" ] || git clone https://github.com/zsh-users/zsh-history-substring-search "$ZSH_CUSTOM/plugins/zsh-history-substring-search"
[ -d "$ZSH_CUSTOM/plugins/zsh-completions" ]              || git clone https://github.com/zsh-users/zsh-completions              "$ZSH_CUSTOM/plugins/zsh-completions"

# powerlevel10k
brew list powerlevel10k >/dev/null 2>&1 || brew install powerlevel10k

rm -rf "$HOME/.p10k.zsh"
ln -s "$DOTFILES/zsh/p10k.zsh" "$HOME/.p10k.zsh"

